raw_data_path = "D:\\Data\\Classical-Modern-main\\Classical-Modern-main"  # 原始数据路径地址
max_length = 100  # 文本最大长度(基于文本长度分布进行设置)
batch_size = 64  # 单批次数据大小
num_workers = 0  # 对于Windows用户，这里应设置为0，否则会出现多线程错误
use_cache = True  # 是否使用缓存
d_model = 512  # 词嵌入维度 todo 后期升级显卡后把数调大点
epochs = 10  # 训练轮次
model_checkpoint = None  # 模型检查点 todo 在此处手动赋值
model_dir = "./runs/models"
